name: 'npm-semver-publish'

description:
  'npm publish with semanantic versioning rules'

author: 'iuccio'

branding:
  color: blue
  icon: package

inputs:
  target-branch:
    description:
      'Branch name new release should be executed'
    required: true
    default: 'master'

outputs:
  version:
    description: 'Published release version'

runs:
  using: node20
  main: dist/index.js
