name: 'npm-semver-publish'

description: 'npm publish with semanantic versioning rules'

author: 'iuccio'

branding:
  color: blue
  icon: package

inputs:
  target-branch:
    description: 'Branch name new release should be executed'
    required: true
    default: 'master'
  provenance:
    description:
      'Allows you to publicly establish where a package was built and who
      published a package'
    required: false
    default: 'false'

outputs:
  version:
    description: 'Published release version'

runs:
  using: node20
  main: dist/index.js
